# fly.toml app configuration file generated for your SolidStart image service
# See https://fly.io/docs/reference/configuration/

app = 'techchallenge-22082025'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[http_service.checks]]
  grace_period = '30s'
  interval = '30s'
  method = 'GET'
  timeout = '10s'
  path = '/'
  headers = { }

[machine]
  cpu_kind = 'shared'
  cpus = 2
  memory = '4gb'

[[restart]]
  policy = 'on-failure'

[deploy]
  release_command = 'echo "Deployment starting..."'
  strategy = 'rolling'
  max_unavailable = 0.5